### ISSUE TITLE
Paid help

### ISSUE THREAD

**Issue by zhaocaijinbao1314** [dexpiper/tabletopdicebot#3]
The result of the telegram dice thrown out shows that it can be preset in advance?

**Comment by dexpiper** [comment]
I'm sorry but I'm not sure I understood you right. Could you please describe your issue in a more clear way: what are you trying to do, what are you expecting to get and what you've got instead? Any logs or screenshots are welcome.
Thank you in advance.

UPDATE:
In case you're seeking for something like saving your custom throw presets (if I got it right), I'm currently expanding this project and planning to add this exact feature in June, 2022. It would be free for all users.

**Comment by dexpiper** [comment]
Version 2.0 supports this feature.

**Comment by dexpiper** [comment]
Version 2.0 supports this feature.

**Comment by zhaocaijinbao1314** [comment]
I need to predict the number of dice in advance or customize the number of dice.
________________________________
发件人: Alex Kurilov ***@***.***>
发送时间: Sunday, May 15, 2022 8:07:51 PM
收件人: dexpiper/tabletopdicebot ***@***.***>
抄送: zhaocaijinbao1314 ***@***.***>; Author ***@***.***>
主题: Re: [dexpiper/tabletopdicebot] Paid help (Issue #3)


I'm sorry but I'm not sure I understood you right. Could you please describe your issue in a more clear way: what are you trying to do, what are you expecting to get and what you've got instead? Any logs or screenshots are welcome.
Thank you in advance.

―

**Comment by dexpiper** [comment]
So you'd like to cheat, eh?)

**Comment by zhaocaijinbao1314** [comment]
Can you leave your contact information? Telegram?
________________________________
发件人: e88f88 e88f88 ***@***.***>
发送时间: Thursday, June 16, 2022 6:54:01 PM
收件人: dexpiper/tabletopdicebot ***@***.***>; dexpiper/tabletopdicebot ***@***.***>
抄送: Author ***@***.***>
主题: Re: [dexpiper/tabletopdicebot] Paid help (Issue #3)

You can also think so. I'm more concerned about whether it can be realized.
________________________________
发件人: Alex Kurilov ***@***.***>
发送时间: Thursday, June 16, 2022 6:52:58 PM
收件人: dexpiper/tabletopdicebot ***@***.***>
抄送: zhaocaijinbao1314 ***@***.***>; Author ***@***.***>
主题: Re: [dexpiper/tabletopdicebot] Paid help (Issue #3)


So you'd like to cheat, eh?)

―

**Comment by dexpiper** [comment]
I am @dexpiper in Telegram, please feel free to contact me. But I should point out that I do not like cheats and would not add them anyway, if you're up to it)

**Comment by zhaocaijinbao1314** [comment]
You can also think so. I'm more concerned about whether it can be realized.
________________________________
发件人: Alex Kurilov ***@***.***>
发送时间: Thursday, June 16, 2022 6:52:58 PM
收件人: dexpiper/tabletopdicebot ***@***.***>
抄送: zhaocaijinbao1314 ***@***.***>; Author ***@***.***>
主题: Re: [dexpiper/tabletopdicebot] Paid help (Issue #3)


So you'd like to cheat, eh?)

―
